# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
name:             yummyml.com
title:            Yummy
tagline:          'Yummy'
description:      'Yummy extension'
url:              https://www.yummyml.com
baseurl:          /
relative_url:     /
remote_theme:     just-the-docs/just-the-docs
color_scheme:     dark
logo:             "/assets/images/yummy_logo.png"

author:
  name:           'Qooba'
  url:            https://blog.qooba.net/about

paginate:         5

# Custom vars

aux_links:
  "Yummy on GitHub":
    - "//github.com/yummyml/yummy"

github:
  repo:           https://github.com/yummyml/yummy

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag


ga_tracking: G-3X1WNGVLQ7
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: "default"

#theme: jekyll-theme-slate
#theme: minimal-mistakes-jekyll
